# 실전 적용!!!

In [3]:
# numpy import하기


## 1. NumPy 배열 생성

In [5]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기 #변수 명은 자유!


array([1, 2, 3, 4, 5])

In [6]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기


(dtype('int32'), (5,), 5, 1)

In [7]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기


array([1, 2, 3, 4, 5])

In [11]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [82]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성


array([[0.99333839, 0.35521962, 0.06053264, 0.25356564],
       [0.2306351 , 0.73361236, 0.62446521, 0.71387271],
       [0.71352723, 0.17271954, 0.34270488, 0.70510633]])

## 2. 산술연산

In [19]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기


(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [20]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기


(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [23]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기


(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [24]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기


(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [25]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기


array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [26]:
# 행렬곱셈(dot product) 연산하기


array([[245, 260],
       [620, 660]])

## 3. Aggregation 함수

In [28]:
# 1~10까지 이루어진 1차원 배열 생성하기


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# 최대값, 최소값 출력하기


(10, 1)

In [31]:
# 배열요소의 합, 평균값 출력하기


(55, 5.5)

In [32]:
# 중앙값(중위값), 표준편차 출력하기


(5.5, 2.8722813232690143)

In [34]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
# 각 행의 max값, min값 출력하기


(array([ 5, 10, 15, 20]), array([ 1,  6, 11, 16]))

In [36]:
# 각 열의 max값, min값 출력하기


(array([16, 17, 18, 19, 20]), array([1, 2, 3, 4, 5]))

In [37]:
# 각 행의 sum값 출력하기


array([15, 40, 65, 90])

In [38]:
# 각 열의 sum값 출력하기


array([34, 38, 42, 46, 50])

## 4. 인덱싱과 슬라이싱

In [61]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
# 위 배열에서 7을 인덱싱하기


7

In [63]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)


14

In [64]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기


array([6, 7])

In [65]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기


array([ 7, 12])

In [66]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기


array([[3, 4],
       [8, 9]])

In [69]:
# 위 배열에서 3의 배수 찾기


array([ 0,  3,  6,  9, 12])

In [71]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기


array([ 1,  5,  9, 13])

In [73]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기


array([9])